### ISSUE TITLE
some bug 

### ISSUE THREAD

**Issue by Jarlene** [metacarbon/attentionReasoning-llm#1]
![image](https://github.com/metacarbon/attentionReasoning-llm/assets/14009650/69ba2f60-dfde-4179-8a7e-66926e8203fc)

in layer_idx =0 ,the self.first_layer_mask init。but layer_idx !=0 self.first_layer_mask is none， not equal self.first_layer_mask of the layer_idx=0， which is different with the paper

**Comment by metacarbon** [comment]
Thanks, I want to make it clear that self.first_layer_mask is initialized when layer_id == 0, and this mask is then used for all subsequent layers to resemble the attention pattern of the first layer. 

In the code snippet, when layer_id > 0, the self.first_layer_mask is not re-initialized or modified; instead, it directly uses the mask created in the first layer.

**Comment by Jarlene** [comment]
> Thanks, I want to make it clear that self.first_layer_mask is initialized when layer_id == 0, and this mask is then used for all subsequent layers to resemble the attention pattern of the first layer.
> 
> In the code snippet, when layer_id > 0, the self.first_layer_mask is not re-initialized or modified; instead, it directly uses the mask created in the first layer.
---------------------------
I know what you mean ，   but subsequent layers can not use first layer mask, because all attentions in layers is independent。you should set it in LlamaModel when loop the layers。

**Comment by metacarbon** [comment]
I see, it becomes self boosting. I fixed it and added alpha value to control the magnitude since I am using a brute force way to re-balance the attention scores. An ideal way should be normalizing them after re-balance. Thank you so much!
